FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile && npx prisma generate

# Copy source code
COPY . .

# Build the app
RUN pnpm run build

# Expose port 4567
EXPOSE 4567

# Start the app
CMD ["pnpm", "run", "start", "--", "-p", "4567"]

